server:
  port: 9527
spring:
  application:
    name: ruigou-zuul-gateway-test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  routes:
    plat.serviceId: ruigou-plat #这是调用满足条件的服务名，注意要小写
    plat.path: /plat/** #这是所有路径前的通配
    commodity.serviceId: ruigou-commodity #这是调用满足条件的服务名，注意要小写
    commodity.path: /commodity/** #这是所有路径前的通配
    common.serviceId: ruigou-common #这是调用满足条件的服务名，注意要小写
    common.path: /common/** #这是所有路径前的通配
  ignored-services: "*" #用*来通配符，忽略从9527端口通过服务名来调用
  prefix: "/services" #这是所有路径的前缀
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1